### ISSUE TITLE
How to center the frames on the screen?

### ISSUE THREAD

**Issue by deadtrickster** [alphapapa/yequake#1]
Frames are perfectly aligned at the horizontal middle of the screen, How to align at the vertical middle (i.e. I would like to have my scratch buffer perfectly centered both horizontally and vertically)? Also would be cool if all parameters can be either constants or functions, like even yequake-frames can hold both.
Thanks for the lib :-)

**Comment by deadtrickster** [comment]
something like `(frame-y (floor (/ (- monitor-height frame-height) 2)))`, cons is hardcoded of course

**Comment by alphapapa** [comment]
Hi Ilya,

I left those out, I guess because I wasn't using them myself.  The commit I just pushed seems to work.  Please let me know if it takes care of it for you.

I tried to pass `left` and `top` simply as frame parameters, which wouldn't have required any changes to Yequake, but on my system, it didn't always work correctly when using float ratios, so this commit handles it in a way that seems to always work.  Here's the code I used to test with:

```el
(let ((yequake-frames
       (list
        (cons "test" (list
                      (cons 'name "test")
                      (cons 'buffer-fns
                            '("~/org/temp.org"
                              split-window-horizontally
                              org-now
                              (lambda nil
                                (select-window
                                 (get-buffer-window
                                  (find-buffer-visiting "~/org/temp.org"))))))
                      (cons 'height 0.75)
                      (cons 'width 0.75)
                      (cons 'top 0.5)
                      (cons 'left 0.5)
                      (cons 'alpha 0.95)
                      (cons 'frame-parameters
                            (list
                             (cons 'user-position t)
                             (cons 'undecorated t)
                             (cons 'skip-taskbar t)
                             (cons 'sticky t))))))))
  (yequake-toggle "test"))
```

Thanks for the suggestion.

BTW, I'd love to hear about how you're using Yequake, what kinds of frames you may design with it.  I think there are more uses than I can think of right now...
